### PR TITLE
Treat grants as a Set instead of List to avoid ordering-based changes detection.

### LINKED ISSUE #6: [Bug] Unapplied list of grants changes detected based on ordering
After provisioning a few databases, user and grants for multiple databases, Terraform detects un-applied changes to reorder grants which makes no sense.
```
$ terraform plan
<...>
  ~ module.common.influxdb_user.grafana
      grant.0.database: "consul" => "telegraf"
      grant.1.database: "namerd" => "consul"
      grant.2.database: "telegraf" => "namerd"
      grant.4.database: "linkerd" => "nomad"
      grant.5.database: "nomad" => "linkerd"
<...>
```
### Terraform Version
```
$ terraform -v
Terraform v0.11.7
+ provider.influxdb v1.0.0
```

### Affected Resource(s)
- influxdb_user

### Terraform Configuration Files
Any configuration with a user having multiple grants to different databases

### Debug Output
https://gist.github.com/olgert/4ef79545603e6f4e806652904b8141fd

### Panic Output
N/A

### Expected Behavior
No changes to apply

### Actual Behavior
Terraform tries to apply different ordering of grants

### Steps to Reproduce
1. Have any configuration with a user having multiple grants to different databases
2. `terraform apply`
3. `terraform plan`

### Important Factoids
N/A

### References
N/A

### PR DESCRIPTION
**Pull request by olgert**
Fixes #6 
1. Treat grants as a Set instead of List to avoid ordering-based changes detection.
2. [Extra] Treat 'ALL' and 'ALL PRIVILEGES' as the same level of grant.

### CODE REVIEW

**Comment by sidgod** [comment]
Change looks good.

File: influxdb/resource_user.go [hunk 1]
```diff
@@ -167,7 +167,7 @@ func readGrants(d *schema.ResourceData, meta interface{}) error {
 		if result[1].(string) != "NO PRIVILEGES" {
 			var grant = map[string]string{
 				"database":  result[0].(string),
-				"privilege": strings.ToLower(result[1].(string)),
+				"privilege": strings.Replace(strings.ToLower(result[1].(string)), "all privileges", "all", 1),
```
Comment (catsby) [inline influxdb/resource_user.go]: `strings.ToLower` here is lowercasing all the grant strings and storing them as lowercase in the state file. Grants like these:

```hcl
grant {
  database  = "${influxdb_database.green.name}"
  privilege = "ALL"
}

grant {
  database  = "${influxdb_database.blue.name}"
  privilege = "WRITE"
}
```

Result in a reoccuring diff:

```
  ~ influxdb_user.test
      grant.2079896074.database:  "" => "terraform-blue"
      grant.2079896074.privilege: "" => "WRITE"
      grant.2960020804.database:  "terraform-blue" => ""
      grant.2960020804.privilege: "write" => ""
      grant.3779313284.database:  "" => "terraform-green"
      grant.3779313284.privilege: "" => "ALL"
      grant.3971511288.database:  "terraform-green" => ""
      grant.3971511288.privilege: "all" => ""
```

I looked at the InfluxDB docs, and they suggest these values are always uppercase, though I don't recall seeing something explicitly saying they will always be upper case 🤔 

The example grants in the [documentation for the resource](https://www.terraform.io/docs/providers/influxdb/r/user.html#grant) use upper case, so I recommend we use a validation function for the input to ensure uppercase is used. Here's an example of a validation func in use:

- https://github.com/terraform-providers/terraform-provider-aws/blob/879ea1bed3ff54c48ffbb64bbfd9244bc7b98720/aws/resource_aws_iam_role.go#L65-L77

File: influxdb/resource_user.go [hunk 2]
```diff
@@ -190,8 +190,8 @@ func updateUser(d *schema.ResourceData, meta interface{}) error {
 
 	if d.HasChange("grant") {
 		oldGrantV, newGrantV := d.GetChange("grant")
-		oldGrant := oldGrantV.([]interface{})
-		newGrant := newGrantV.([]interface{})
+		oldGrant := oldGrantV.(*schema.Set).List()
+		newGrant := newGrantV.(*schema.Set).List()
 
 		for _, oGV := range oldGrant {
```
Comment (catsby) [inline influxdb/resource_user.go]: Because these are now `TypeSet`, we can optionally use the `Difference` method:

- https://github.com/hashicorp/terraform/blob/9441e78fb9c35037da71fd0284b97e546dd6a53b/helper/schema/set.go#L109-L120

That could simplify or remove some of this logic. Don't feel required to do so though 😄

**Comment by olgert** [comment]
@catsby Grants in InfluxDB are indeed appear uppercase in all documentation/references. InfluxQL itself is case insensitive, but if we have to enforce some a style, it's going to be uppercase for sure :) Please go ahead and review my recent commit. As of utilizing Difference function to drop some of custom logic code - I like that idea, but that could be a separate PR, just to resolve the issue for now.

**Comment by olgert** [comment]
Good! Someone with write permissions should merge the PR then.

**Comment by catsby** [comment]
This is merged and released, thanks!

**Comment by olgert** [comment]
Thanks for the release!

**Comment by jareware** [comment]
Have not seen it since upgrading.
